#!/usr/bin/env bash

if ! which podman > /dev/null; then
	echo "docker needs to be installed"
	exit 1
fi

: ${IMAGE:?"Need to set IMAGE, e.g. quay.io/coreos/vault-operator"}

echo "building container..."
podman build --tag "${IMAGE}" -f Dockerfile . 1>/dev/null

#echo "pushing container..."
#podman push "${IMAGE}" 1>/dev/null
